// Generated by Selenium IDE

using System;
using System.Collections.Generic;
using System.Drawing;
using OpenQA.Selenium;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Interactions;
using Xunit;

namespace WebserverTests.Selenium.Tests
{
    public class NavigateTestSiteTests : IDisposable
    {
        public IWebDriver driver { get; private set; }
        public IDictionary<String, Object> vars { get; private set; }
        public IJavaScriptExecutor js { get; private set; }

        public NavigateTestSiteTests()
        {
            driver = new FirefoxDriver();
            js = (IJavaScriptExecutor)driver;
            vars = new Dictionary<String, Object>();
        }

        public void Dispose()
        {
            driver.Quit();
        }

        // [Fact(Skip = "Test")]
        public void NavigateTestSite()
        {
            driver.Navigate().GoToUrl("http://localhost:8089/a.html");
            driver.Manage().Window.Size = new Size(550, 691);
            driver.FindElement(By.LinkText("do simple relative internal links work?")).Click();
            driver.FindElement(By.LinkText("back")).Click();
            driver.FindElement(By.LinkText("do general relative links work")).Click();
            driver.FindElement(By.LinkText("back")).Click();
            driver.FindElement(By.LinkText("do simple absolute links work")).Click();
            driver.FindElement(By.LinkText("back")).Click();
            driver.FindElement(By.LinkText("do general absolute links work")).Click();
            driver.FindElement(By.LinkText("back")).Click();
            driver.FindElement(By.LinkText("do URLs with spaces work")).Click();
            driver.FindElement(By.LinkText("back")).Click();
            driver.FindElement(By.CssSelector("tr:nth-child(7) > td:nth-child(1)")).Click();
            driver.FindElement(By.CssSelector("tr:nth-child(7) > td:nth-child(1)")).Click();
            {
                var element = driver.FindElement(By.CssSelector("tr:nth-child(7) > td:nth-child(1)"));
                Actions builder = new Actions(driver);
                builder.DoubleClick(element).Perform();
            }
            driver.FindElement(By.LinkText("do URLs with %20 work")).Click();
            driver.FindElement(By.CssSelector("html")).Click();
            driver.FindElement(By.LinkText("back")).Click();
        }
    }
}
