// Generated by Selenium IDE

using System;
using System.Collections.Generic;
using OpenQA.Selenium;
using OpenQA.Selenium.Firefox;
using Xunit;

namespace WebserverTests.Selenium.Tests
{
    public class Navigate404Tests : IDisposable
    {
        public IWebDriver driver { get; private set; }
        public IDictionary<String, Object> vars { get; private set; }
        public IJavaScriptExecutor js { get; private set; }

        public Navigate404Tests()
        {
            driver = new FirefoxDriver();
            js = (IJavaScriptExecutor)driver;
            vars = new Dictionary<String, Object>();
        }

        public void Dispose()
        {
            driver.Quit();
        }

        [Fact]
        public void Navigate404()
        {
            driver.Navigate().GoToUrl("http://localhost:8089/unknown.html");
        }
    }
}
